version: "3.3"

services:
  yolo:
    build: ./yolo-client
    container_name: yolo
    volumes:
      - ./yolo-client:/workspace
    env_file:
      - common.env
    stdin_open: true
    tty: true
  
  gst:
    build: ./gstreamer-sandbox/src
    container_name: gst
    volumes:
      - ./gstreamer-sandbox/src:/workspace
    env_file:
      - common.env
    stdin_open: true
    tty: true